### ISSUE TITLE
 VirtualBox additional disk example does not work

### ISSUE THREAD

**Issue by omry** [test-kitchen/kitchen-vagrant#387]
Using the example from the main readme as is, it vm fails to start with
> VBoxManage: error: VDI: cannot create image '/tmp/disk1.vmdk' (VERR_ALREADY_EXISTS)
Deleting the file does not solve the problem.

Vagrant file:
https://pastebin.com/7uQ6WkAv

Output:
https://pastebin.com/6jFqVgZ0

(Did not paste here due to formatting issues).

Versions:

$ chef -v
Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112

$ VBoxManage  -v
5.2.20r125813

**Comment by stissot** [comment]
Hello,

If you still have the issue, can you try to remove the following lines from `.kitchen.yml`, I believe this is not needed

```
 storagectl:
      - name: IDE Controller
        portcount: 4
```

**Comment by ptiggerdine** [comment]
Hi,
I've run into this problem as well. my requirement is for 4 disk for an oracle db ASM verification test of puppet manifest. We added a separate storage controller. The error we get would suggest that there's a race condition in the adding for storage in general. We get varying issue with vagrant saying that files, drives or storage controllers already exist.  


       A customization command failed:
       ["storagectl", :id, "--name", "SAS", "--add", "SAS", "--controller", "LSILogicSAS", "--portcount", 6]

       The following error was experienced:

       #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
       for controlling VirtualBox. The command and stderr is shown below.

       Command: ["storagectl", "7935ea4e-750b-43a9-897a-bb3df1d88089", "--name", "SAS", "--add", "SAS", "--controller", "LSILogicSAS", "--portcount", "6"]

       Stderr: VBoxManage.exe: error: Storage controller named 'SAS' already exists
       VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee IUnknown
       VBoxManage.exe: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SAS, ctl.asOutParam())" at line 1098 of file VBoxManageStorageController.cpp
       >

This is the customise code section

      storagectl:
      - name: "SAS"
        add: "SAS"
        controller: "LSILogicSAS"
        portcount: 6
      createhd:
      - filename: "box-disk002.vdi"
        size: 10240
        format: VDI
      - filename: "box-disk101.vdi"
        size: 10240
        format: VDI
      - filename: "box-disk102.vdi"
        size: 10240
        format: VDI
      - filename: "box-disk201.vdi"
        size: 10240
        format: VDI
      - filename: "box-disk202.vdi"
        size: 10240
        format: VDI
      storageattach:
      - storagectl: SATA
        port: 1
        device: 0
        type: hdd
        medium: "box-disk002.vdi"
        hotpluggable: "on"
      - storagectl: SAS
        port: 1
        device: 0
        type: hdd
        medium: "box-disk101.vdi"
        hotpluggable: "on"
      - storagectl: SAS
        port: 2
        device: 0
        type: hdd
        medium: "box-disk102.vdi"
        hotpluggable: "on"
      - storagectl: SAS
        port: 3
        device: 0
        type: hdd
        medium: "box-disk201.vdi"
        hotpluggable: "on"
      - storagectl: SAS
        port: 4
        device: 0
        type: hdd
        medium: "box-disk202.vdi"
        hotpluggable: "on"

**Comment by stissot** [comment]
@ptiggerdine: Your storage configuration looks correct. this is indeed a bug of kitchen-vagrant. PR #389 should fix the error, it's not merged yet but meanwhile could you please test by installing the driver from source using this branch: https://github.com/Ecodev/kitchen-vagrant/tree/createhd_existing

Assuming your system PATH is configured to use ChefDK's ruby, the procedure would be something like:

```
git clone --branch createhd_existing https://github.com/Ecodev/kitchen-vagrant.git
cd kitchen-vagrant
bundle install --path vendor/bundle
./vendor/bundle/ruby/2.6.0/bin/rake test
gem build kitchen-vagrant.gemspec 
gem install kitchen-vagrant-1.6.1.gem
```

**Comment by marcparadise** [comment]
Pr #389 does look like it will resolve this issue, but there is some trailing work to be completed before we can merge that PR.  We'll update this issue once it lands.

**Comment by drlkf** [comment]
I'm still encountering this issue on `1.14.1`:

`.kitchen.yml`:
```
    driver:
      customize:
        createhd:
          - filename: disk1.vdi
            format: VDI
            size: 1024
        storageattach:
          - storagectl: SATA Controller
            port: 1
            device: 0
            type: hdd
            medium: disk1.vdi
```

Generated `Vagrantfile`:
```
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-server-ceph-osd-debian-12-226772c3-9035-4091-84bc-b7ad537cd1b1"
    p.customize ["modifyvm", :id, "--audio", "none"]
    unless File.file?("disk1.vdi")
      p.customize ["createhd", "--filename", "disk1.vdi", "--size", 1024]
    end
    p.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "disk1.vdi"]
  end
```

Error output:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/debian-12' version '202306.13.0' is up to date...
==> default: Setting the name of the VM: kitchen-server-ceph-osd-debian-12-226772c3-9035-4091-84bc-b7ad537cd1b1
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
STDERR: A customization command failed:

["createhd", "--filename", "disk1.vdi", "--size", 1024]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["createhd", "--filename", "disk1.vdi", "--size", "1024"]

Stderr: 0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Failed to create medium
VBoxManage: error: Could not create the medium storage unit '/home/drlkf/.local/share/work/server/.kitchen/kitchen-vagrant/ceph-osd-debian-12/disk1.vdi'.
VBoxManage: error: VDI: cannot create image '/home/drlkf/.local/share/work/server/.kitchen/kitchen-vagrant/ceph-osd-debian-12/disk1.vdi' (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage: error: Context: "RTEXITCODE handleCreateMedium(HandlerArg*)" at line 510 of file VBoxManageDisk.cpp
```
I made sure the disk file does not exist before `kitchen create`, but the issue still appears.
